version: '3.8'

services:
  mongodb:
    image: mongo:4.4.20-focal
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: laurin
      MONGO_INITDB_ROOT_PASSWORD: laurin
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      MONGO_DB: todo   # oder der Name, den du für die MongoDB-Datenbank gewählt hast
      MONGO_USER: laurin
      MONGO_PASSWORD: laurin
      MONGO_HOST: mongodb       # Container-Name des MongoDB-Containers
      MONGO_PORT: 27017         # MongoDB-Standardport
      PORT: 8080
      GIN_MODE: release
    ports:
      - "8080:8080" 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090

volumes:
  mongodb-data:
    driver: local

networks:
  localprom:
    driver: bridge
