version: '3.8'

services:
  todo-api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - .:/app
    restart: unless-stopped
