# Use an official Go image as a build stage
FROM golang:1.22-alpine AS build

# Set the current working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the container
COPY go.mod go.sum ./

# Download all Go modules
RUN go mod download

# Build the Go app
RUN go build -o todo-crud-api .

# Final stage
FROM alpine:latest

# Set the working directory inside the container
WORKDIR /root/

# Copy the binary from the build stage
COPY --from=build /app/todo-crud-api .

# Expose port 8080
EXPOSE 8080

# Command to run the executable
CMD ["./todo-crud-api"]
