global:
  scrape_interval: 30s # Set the global scrape interval to 30 seconds
  evaluation_interval: 30s # Evaluate rules every 30 seconds

scrape_configs:
  - job_name: 'custom_targets'
    scrape_interval: 30s # Set scrape interval for this job specifically (optional if global already set)
    static_configs:
      - targets:
          - '27017:27017'
          - '8080:8080'
          - '3000:3000'
          - '9090:9090'